### ISSUE TITLE
Incorrect camel case used

### ISSUE THREAD

**Issue by purnendudash** [MoodEasy/moodle-local_meccertbulkdownload#6]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

https://github.com/MoodEasy/moodle-local_meccertbulkdownload/blob/07b45cff5bb6e3c3ac483ef4a8c0dda358da73ed/lang/en/local_meccertbulkdownload.php#L90

**Comment by MoodEasy** [comment]
I checked that all other strings are sentence case.
We'd like to keep just the plugin name with camel case.
